module

public import Mathlib

public import AISafetyMath.Solutions.IB_RL
public import AISafetyMath.Solutions.IB.CredalSets
public import AISafetyMath.Solutions.IB.TrajectoryMeasure

/-!
This file formalizes the definitions and propositions in
Articles/IB_Basics.md

The main result is `IB.continuous_of_CCL`.
It also includes a number of sanity-check lemmas.

As with `IB_RL`, to keep this file readable the definitions and long proofs live in
helper files in this directory, which this file re-exposes:

* `AISafetyMath.Solutions.IB.CredalSets` — the `IB` namespace development of credal sets:
  the metric space `Δ X` of probability measures (`convergence_iff_weak`), convexity of
  sets of probability measures (`ProbConvex`, `probConvex_iff`), the type `Credal X`
  of nonempty compact convex sets and its constructor `Credal.byClosedConvexHull`,
  and the Lévy–Prokhorov machinery used for continuity.

The crisp causal laws (the infra-kernel generated by a set of environments,
`IB.infraKernelOfEnvironments`, and Proposition 1 `IB.continuous_of_CCL`)
live in this file, before the sections that use them: the elaborator's nested-proof cache
is per module, so the `Credal (Destiny A O)` instance proofs must be created here in order
to be shared — under the same auxiliary names as in the challenge file — with `expCCL` and
everything downstream of it. The uniform-continuity machinery those proofs rely on lives in
`AISafetyMath.Solutions.IB.TrajectoryMeasure` and `AISafetyMath.Solutions.IB.CredalSets`.

The reinforcement-learning definitions it builds on come transitively through
`AISafetyMath.Solutions.IB_RL`.
-/

@[expose] public section


namespace IB

open ProbabilityTheory MeasureTheory

section CrispCausalLaws

open IB_RL

variable {A O : Type*}
variable [Finite A] [Finite O]

/- we use discrete measurable and topological spaces on A and O -/
variable [MeasurableSpace A] [MeasurableSpace O]
variable [DiscreteMeasurableSpace A] [DiscreteMeasurableSpace O]
variable [TopologicalSpace A] [DiscreteTopology A]
variable [TopologicalSpace O] [DiscreteTopology O]


/- Instances making `Destiny A O` a compact metric Borel space and `Policy A O` a
topological space. These mirror the challenge file's local instances declaration by
declaration (same names, same `[Finite]`-only context, same bodies) so that the
statements below elaborate to literally the same terms as the challenge's; the
comparator requires syntactic equality of the elaborated statements. The root-level
instances in `Solutions.IB.TrajectoryMeasure` are definitionally equal, but being
declared in a richer variable context they elaborate to different terms.

They are also declared with a raised priority so that they win over the imported
root-level ones during instance synthesis. -/

noncomputable scoped
instance (priority := 2000) instDestinyMetric : MetricSpace (Destiny A O) := PiNat.metricSpace


noncomputable scoped
instance (priority := 2000) instPolicyTS : TopologicalSpace (Policy A O) := Pi.topologicalSpace

/- sanity check: the metric given by `PiNat.metricSpace` is `2 ^ (-t)`, where `t` is the
first index at which the two destinies differ. -/
set_option linter.unusedSectionVars false in
lemma ok_destinyMetric (h1 h2 : Destiny A O) (t : ℕ)
    (ht_ne : h1 t ≠ h2 t)
    (ht_eq : ∀ s < t, h1 s = h2 s) :
    dist h1 h2 = (2 : ℝ) ^ (- (t : ℝ)) := by
  have hne : h1 ≠ h2 := fun h => ht_ne (by rw [h])
  -- the hypotheses say exactly that `t` is `PiNat.firstDiff`
  have hfd : PiNat.firstDiff h1 h2 = t := by
    rcases lt_trichotomy (PiNat.firstDiff h1 h2) t with h | h | h
    · exact absurd (ht_eq _ h) (PiNat.apply_firstDiff_ne hne)
    · exact h
    · exact absurd (PiNat.apply_eq_of_lt_firstDiff h) ht_ne
  have hd : dist h1 h2 = (1 / 2 : ℝ) ^ PiNat.firstDiff h1 h2 := PiNat.dist_eq_of_ne hne
  rw [hd, hfd, Real.rpow_neg (by norm_num), Real.rpow_natCast,
    one_div, inv_pow]

/- Crisp Causal Laws: the infra-kernel generated by a set of environments.
Note that we say infraKernel here despite not yet knowing that the map is continuous. -/
noncomputable
def infraKernelOfEnvironments (E : Set (Environment A O)) (hne : E.Nonempty)
    (π : Policy A O) : Credal (Destiny A O) :=
    Credal.byClosedConvexHull
      ( (fun μ => trajectoryProbMeasure π μ) '' E)
      (Set.Nonempty.image (fun μ ↦ trajectoryProbMeasure π μ) hne)

/- sanity check: the infra-kernel generated by a single environment is the singleton
containing that environment's trajectory law (the closed convex hull of a singleton is
that singleton). -/
lemma infraKernel_singleton (μ : Environment A O) (π : Policy A O) :
    (infraKernelOfEnvironments {μ} (Set.singleton_nonempty μ) π).carrier =
    {trajectoryProbMeasure π μ} := by
  change Credal.closedConvexHull ((fun ν => trajectoryProbMeasure π ν) '' {μ}) = _
  rw [Set.image_singleton, Credal.closedConvexHull_singleton]

/- Definition: an infrakernel is a crisp causal law if it is generated by some environments -/
def IsCrispCausalLaw (Λ : Policy A O → Credal (Destiny A O)) : Prop :=
  ∃ (E : Set (Environment A O)) (hne : E.Nonempty), Λ = infraKernelOfEnvironments E hne

/- Because `Policy A O` is a sequential space, to prove continuity it suffices to
prove the crisp causal law is *sequentially* continuous. -/
lemma proposition_1_of_seqContinuous (E : Set (Environment A O)) (hne : E.Nonempty)
    (h : SeqContinuous (infraKernelOfEnvironments E hne)) :
    Continuous (infraKernelOfEnvironments E hne) := by
  have : Fintype A := Fintype.ofFinite A
  have : Fintype O := Fintype.ofFinite O
  exact continuous_iff_seqContinuous.2 h

/- Proposition 1, for the generated infra-kernel:
An infrakernel generated by environments is continuous. -/
theorem infraKernelOfEnvironments_continuous_of_generators
    (E : Set (Environment A O)) (hne : E.Nonempty) :
    Continuous (infraKernelOfEnvironments E hne) := by
  have : Fintype A := Fintype.ofFinite A
  have : Fintype O := Fintype.ofFinite O
  apply proposition_1_of_seqContinuous
  intro π π₀ hconv
  -- The generating sets of the two credal carriers.
  set S : ℕ → Set (Δ (Destiny A O)) :=
    fun k => (fun μ => trajectoryProbMeasure (π k) μ) '' E with hS
  set S₀ : Set (Δ (Destiny A O)) :=
    (fun μ => trajectoryProbMeasure π₀ μ) '' E with hS₀
  -- LP-Hausdorff distance of the *generating* sets → 0, squeezed by the sup-over-`μ` bound (L4).
  have hSlp : Filter.Tendsto
      (fun k => Metric.hausdorffDist (lpEquiv '' S k) (lpEquiv '' S₀)) Filter.atTop (nhds 0) := by
    refine squeeze_zero (fun k => Metric.hausdorffDist_nonneg) (fun k => ?_)
      (trajectory_dist_iSup_tendsto_lp E π π₀ hconv)
    have e1 : lpEquiv '' S k = (fun μ => lpEquiv (trajectoryProbMeasure (π k) μ)) '' E := by
      rw [hS, Set.image_image]
    have e2 : lpEquiv '' S₀ = (fun μ => lpEquiv (trajectoryProbMeasure π₀ μ)) '' E := by
      rw [hS₀, Set.image_image]
    rw [e1, e2]
    exact hausdorffDist_image_le_biSup _ _ E hne
  -- Assemble: generating-set convergence → carrier convergence (IL7) → abstract metric (IL2).
  rw [tendsto_iff_dist_tendsto_zero]
  exact hausdorffDist_tendsto_zero_of_lp (hausdorffDist_lp_carrier_tendsto_zero hSlp)

/- Proposition 1:
Any Crisp Causal Law is continuous. -/
theorem continuous_of_CCL (Λ : Policy A O → Credal (Destiny A O))
    (h : IsCrispCausalLaw Λ) : Continuous Λ := by
  obtain ⟨E, hne, rfl⟩ := h
  exact infraKernelOfEnvironments_continuous_of_generators E hne

end CrispCausalLaws

section MiniMax

variable {X : Type*}
variable [MetricSpace X] [CompactSpace X] [MeasurableSpace X] [BorelSpace X]

/--
Infra-Bayesian Expectation:
Given a credal set `Θ` and a loss function `f`,
choose the worst (largest) expectation among `θ ∈ Θ`.
Note that `sSup` has junk value `0` for sets that are unbounded above.
The integral also has a junk value of `0` if not integrable.
These junk values are not a problem if `f` is measurable and bounded.
-/
noncomputable
def expIB (Θ : Credal X) (f : X → ℝ) : ℝ :=
  sSup ((fun θ => ∫ x, f x ∂θ.toMeasure) '' Θ.carrier)


set_option linter.unusedSectionVars false in
/-- sanity check:
If `f` is bounded and measurable, then it is integrable for all probability measures.
-/
lemma exp_well_defined_of_measurable_bounded (f : X → ℝ)
    (hm : Measurable f)
    (hb1 : BddBelow (Set.range f)) (hb2 : BddAbove (Set.range f))
    (θ : Δ X) :
    Integrable f θ.toMeasure := by
  obtain ⟨a, ha⟩ := hb1
  obtain ⟨b, hb⟩ := hb2
  refine Integrable.of_bound hm.aestronglyMeasurable (max |a| |b|) ?_
  filter_upwards with x
  rw [Real.norm_eq_abs, abs_le]
  refine ⟨?_, (hb ⟨x, rfl⟩).trans ((le_abs_self b).trans (le_max_right _ _))⟩
  exact (neg_le_neg (le_max_left |a| |b|)).trans ((neg_abs_le a).trans (ha ⟨x, rfl⟩))

/-- sanity check:
If `f` is bounded from above, then `θ ↦ ∫ x, f x ∂θ` is bounded from above.
Thus, the set whose `sSup` is taken in `expIB` is not unbounded above
-/
lemma exp_values_bddAbove_of_bddAbove (Θ : Credal X) (f : X → ℝ) (hb : BddAbove (Set.range f)) :
    BddAbove ((fun θ => ∫ x, f x ∂θ.toMeasure) '' Θ.carrier) := by
  obtain ⟨b, hb⟩ := hb
  -- `max b 0` bounds both the genuine integrals (`≤ b`) and the junk value `0`
  refine ⟨max b 0, ?_⟩
  rintro y ⟨θ, -, rfl⟩
  change ∫ x, f x ∂θ.toMeasure ≤ max b 0
  by_cases hi : Integrable f θ.toMeasure
  · refine le_trans ?_ (le_max_left b 0)
    calc ∫ x, f x ∂θ.toMeasure ≤ ∫ _x, b ∂θ.toMeasure :=
          integral_mono hi (integrable_const b) (fun x => hb ⟨x, rfl⟩)
      _ = b := by simp
  · rw [integral_undef hi]
    exact le_max_right b 0



/-- sanity check:
if `f` is continuous, then the supremum in `expIB` is attained.
-/
lemma expIB_has_max (Θ : Credal X) (f : X → ℝ)
    (hf : Continuous f) :
    ∃ θ ∈ Θ.carrier, expIB Θ f = ∫ x, f x ∂θ.toMeasure := by
  -- on a compact space a continuous `f` is bounded, so it is a bounded continuous function
  have hcont : Continuous (fun θ : Δ X => ∫ x, f x ∂θ.toMeasure) :=
    ProbabilityMeasure.continuous_integral_boundedContinuousFunction
      (BoundedContinuousFunction.mkOfCompact ⟨f, hf⟩)
  -- hence the set of values is a nonempty compact set, and its `sSup` is attained
  have himg := Θ.1.isCompact'.image hcont
  obtain ⟨y, hy⟩ := himg.exists_isGreatest (Θ.1.nonempty'.image _)
  obtain ⟨θ, hθ, rfl⟩ := hy.1
  exact ⟨θ, hθ, hy.csSup_eq⟩


/-! ### Continuity of `expIB` in the credal set

The metric on `Credal X` is the Hausdorff distance (see `CredalSets.lean`), and
`g : θ ↦ ∫ x, f x ∂θ` is continuous on the compact space `Δ X`, hence *uniformly*
continuous.  So if `Θ₁` and `Θ₂` are Hausdorff-close, every point of one is metrically
close to a point of the other, and therefore the two suprema of `g` are close.
The proof is split into the three obvious steps.
-/

/-- Every value `∫ f ∂θ` for `θ ∈ Θ` is below the infra-Bayesian expectation. -/
lemma le_expIB (Θ : Credal X) (f : X → ℝ) (hb : BddAbove (Set.range f))
    {θ : Δ X} (hθ : θ ∈ Θ.carrier) :
    ∫ x, f x ∂θ.toMeasure ≤ expIB Θ f :=
  le_csSup (exp_values_bddAbove_of_bddAbove Θ f hb) ⟨θ, hθ, rfl⟩

/-- One-sided comparison: if every point of `Θ₁` is `ε`-dominated by some point of `Θ₂`
(as measured by `f`-expectations), then `expIB Θ₁ f ≤ expIB Θ₂ f + ε`. -/
lemma expIB_le_add_of_forall_exists (Θ₁ Θ₂ : Credal X) (f : X → ℝ)
    (hb : BddAbove (Set.range f)) (ε : ℝ)
    (h : ∀ θ₁ ∈ Θ₁.carrier, ∃ θ₂ ∈ Θ₂.carrier,
      ∫ x, f x ∂θ₁.toMeasure ≤ (∫ x, f x ∂θ₂.toMeasure) + ε) :
    expIB Θ₁ f ≤ expIB Θ₂ f + ε := by
  refine csSup_le (Θ₁.nonempty.image _) ?_
  rintro y ⟨θ₁, hθ₁, rfl⟩
  obtain ⟨θ₂, hθ₂, hle⟩ := h θ₁ hθ₁
  have := le_expIB Θ₂ f hb hθ₂
  linarith

/-- Hausdorff distance unfolded: a point of `Θ₁` has an `r`-close partner in `Θ₂`
whenever `dist Θ₁ Θ₂ < r`. -/
lemma exists_mem_dist_lt (Θ₁ Θ₂ : Credal X) {r : ℝ} (hr : dist Θ₁ Θ₂ < r)
    {θ : Δ X} (hθ : θ ∈ Θ₁.carrier) :
    ∃ θ' ∈ Θ₂.carrier, dist θ θ' < r := by
  refine Metric.exists_dist_lt_of_hausdorffDist_lt hθ hr ?_
  exact Metric.hausdorffEDist_ne_top_of_nonempty_of_bounded Θ₁.nonempty Θ₂.nonempty
    Θ₁.1.isCompact'.isBounded Θ₂.1.isCompact'.isBounded

/--
Lemma: `expIB` is continuous in `Θ`
-/
lemma expIB_continuous_in_credal (f : X → ℝ) (hf : Continuous f) :
    Continuous (fun Θ : Credal X => expIB Θ f) := by
  have hb : BddAbove (Set.range f) := (isCompact_range hf).bddAbove
  -- `g θ = ∫ f ∂θ` is continuous on the compact space `Δ X`, hence uniformly continuous
  have hcont : Continuous (fun θ : Δ X => ∫ x, f x ∂θ.toMeasure) :=
    ProbabilityMeasure.continuous_integral_boundedContinuousFunction
      (BoundedContinuousFunction.mkOfCompact ⟨f, hf⟩)
  have huc : UniformContinuous (fun θ : Δ X => ∫ x, f x ∂θ.toMeasure) :=
    CompactSpace.uniformContinuous_of_continuous hcont
  rw [Metric.continuous_iff]
  intro Θ₀ ε hε
  obtain ⟨δ, hδ, hδ'⟩ := Metric.uniformContinuous_iff.1 huc (ε / 2) (by linarith)
  refine ⟨δ, hδ, fun Θ hΘ => ?_⟩
  -- both suprema are within `ε/2` of each other, by the one-sided comparison in both directions
  have key : ∀ Θ₁ Θ₂ : Credal X, dist Θ₁ Θ₂ < δ → expIB Θ₁ f ≤ expIB Θ₂ f + ε / 2 := by
    intro Θ₁ Θ₂ h
    refine expIB_le_add_of_forall_exists Θ₁ Θ₂ f hb _ (fun θ₁ hθ₁ => ?_)
    obtain ⟨θ₂, hθ₂, hd⟩ := exists_mem_dist_lt Θ₁ Θ₂ h hθ₁
    refine ⟨θ₂, hθ₂, ?_⟩
    have := hδ' hd
    rw [Real.dist_eq, abs_lt] at this
    linarith [this.1, this.2]
  have h1 := key Θ Θ₀ hΘ
  have h2 := key Θ₀ Θ (by rwa [dist_comm])
  rw [Real.dist_eq, abs_lt]
  constructor <;> linarith


end MiniMax

section RLSetting

open IB_RL

variable {A O : Type*}
variable [Finite A] [Finite O]

/- we use discrete measurable and topological spaces on A and O -/
variable [MeasurableSpace A] [MeasurableSpace O]
variable [DiscreteMeasurableSpace A] [DiscreteMeasurableSpace O]
variable [TopologicalSpace A] [DiscreteTopology A]
variable [TopologicalSpace O] [DiscreteTopology O]

section InfraRegret

/- we use a continuous loss function -/
variable (L : Destiny A O → unitInterval)

/- expected loss of a policy wrt a CCL -/
noncomputable
def expCCL (Λ : Policy A O → Credal (Destiny A O)) (π : Policy A O) : ℝ :=
  expIB (Λ π) (Subtype.val ∘ L)


/- sanity check:  `expCCL` has values in `unitInterval` -/
lemma expCCL_mem_unitInterval (Λ : Policy A O → Credal (Destiny A O)) (π : Policy A O) :
    expCCL L Λ π ∈ unitInterval := by
  -- every element of the set `expIB` takes the `sSup` of lies in `[0,1]`: the integrand is
  -- `[0,1]`-valued, and the junk value `0` for a non-integrable integrand is also in `[0,1]`.
  have key : ∀ y ∈ (fun θ : Δ (Destiny A O) => ∫ x, (Subtype.val ∘ L) x ∂θ.toMeasure) ''
      (Λ π).carrier, 0 ≤ y ∧ y ≤ 1 := by
    rintro y ⟨θ, -, rfl⟩
    refine ⟨integral_nonneg fun x => (L x).2.1, ?_⟩
    by_cases hi : Integrable (fun x => ((L x : ℝ))) θ.toMeasure
    · calc ∫ x, (Subtype.val ∘ L) x ∂θ.toMeasure
          ≤ ∫ _x, (1 : ℝ) ∂θ.toMeasure := integral_mono hi (integrable_const 1) fun x => (L x).2.2
        _ = 1 := by simp
    · change ∫ x, ((L x : ℝ)) ∂θ.toMeasure ≤ 1
      rw [integral_undef hi]
      norm_num
  exact ⟨Real.sSup_nonneg fun y hy => (key y hy).1,
    Real.sSup_le (fun y hy => (key y hy).2) zero_le_one⟩


/- Defining infra-regret.
Again, using `EReal`
 -/
noncomputable
def infraRegret (Λ : Policy A O → Credal (Destiny A O)) (π : Policy A O) : EReal :=
  (expCCL L Λ π : EReal)
  - ⨅ (π' : Policy A O), (expCCL L Λ π' : EReal)

/- sanity check:  `infraRegret` has values between `0` and `1` -/
lemma infraRegret_mem_unitInterval (Λ : Policy A O → Credal (Destiny A O)) (π : Policy A O) :
    infraRegret L Λ π ∈ {a : EReal | 0 ≤ a ∧ a ≤ 1} := by
  -- the infimum is over a type inhabited by `π`, and is squeezed between `0` and `expCCL L Λ π`,
  -- so it is a finite `EReal` and the whole statement reduces to an inequality in `ℝ`.
  set i : EReal := ⨅ (π' : Policy A O), (expCCL L Λ π' : EReal) with hidef
  have hnn : (0 : EReal) ≤ i :=
    le_iInf fun π' => by exact_mod_cast (expCCL_mem_unitInterval L Λ π').1
  have hle : i ≤ (expCCL L Λ π : EReal) := iInf_le _ π
  have hbot : i ≠ ⊥ := fun h => by simp [h] at hnn
  have htop : i ≠ ⊤ := fun h => by rw [h] at hle; simp at hle
  obtain ⟨r, hr⟩ : ∃ r : ℝ, i = (r : EReal) := ⟨i.toReal, (EReal.coe_toReal htop hbot).symm⟩
  have h0r : (0 : ℝ) ≤ r := by rw [hr] at hnn; exact_mod_cast hnn
  have hrx : r ≤ expCCL L Λ π := by rw [hr] at hle; exact_mod_cast hle
  have hx1 := (expCCL_mem_unitInterval L Λ π).2
  refine ⟨?_, ?_⟩ <;> rw [infraRegret, ← hidef, hr, ← EReal.coe_sub]
  · exact_mod_cast sub_nonneg.2 hrx
  · exact_mod_cast (by linarith : expCCL L Λ π - r ≤ 1)


/- Proposition 2: -/
lemma continuous_expCCL (Λ : Policy A O → Credal (Destiny A O))
    (hL : Continuous L) (hCCL : IsCrispCausalLaw Λ) :
    Continuous (expCCL L Λ) := by
  -- `expCCL L Λ = (fun Θ => expIB Θ (Subtype.val ∘ L)) ∘ Λ`: the outer map is continuous in the
  -- credal set (`expIB_continuous_in_credal`), the inner one is Proposition 1.
  exact (expIB_continuous_in_credal _ (continuous_subtype_val.comp hL)).comp
    (continuous_of_CCL Λ hCCL)

/- The Bayes integrand is integrable: it is `[0,1]`-valued, and measurable because `I` carries
the discrete σ-algebra. -/
lemma integrable_expCCL {I : Type*} [MeasurableSpace I] [DiscreteMeasurableSpace I]
    (ζ : ProbabilityMeasure I) (Λ_fam : I → (Policy A O → Credal (Destiny A O)))
    (π : Policy A O) :
    Integrable (fun i => expCCL L (Λ_fam i) π) ζ.toMeasure := by
  refine Integrable.mono' (integrable_const (μ := ζ.toMeasure) 1)
    Measurable.of_discrete.aestronglyMeasurable (Filter.Eventually.of_forall fun i => ?_)
  have h := expCCL_mem_unitInterval L (Λ_fam i) π
  rw [Real.norm_eq_abs, abs_of_nonneg h.1]
  exact h.2

/- The Bayes loss is continuous in the Policy: `Policy A O` is a sequential space, so it suffices
to pass to the limit along sequences, which dominated convergence (bound `1`) does using
Proposition 2 pointwise in `i`. -/
lemma continuous_integral_expCCL {I : Type*} [MeasurableSpace I] [DiscreteMeasurableSpace I]
    (ζ : ProbabilityMeasure I) (Λ_fam : I → (Policy A O → Credal (Destiny A O)))
    (hL : Continuous L) (hCCL : ∀ i, IsCrispCausalLaw (Λ_fam i)) :
    Continuous (fun π => ∫ i, expCCL L (Λ_fam i) π ∂ζ.toMeasure) := by
  have : Fintype A := Fintype.ofFinite A
  have : Fintype O := Fintype.ofFinite O
  refine continuous_iff_seqContinuous.2 fun {π} {π₀} hconv => ?_
  refine tendsto_integral_of_dominated_convergence (fun _ => 1)
    (fun n => Measurable.of_discrete.aestronglyMeasurable) (integrable_const 1)
    (fun n => Filter.Eventually.of_forall fun i => ?_)
    (Filter.Eventually.of_forall fun i => ?_)
  · have h := expCCL_mem_unitInterval L (Λ_fam i) (π n)
    rw [Real.norm_eq_abs, abs_of_nonneg h.1]
    exact h.2
  · exact (continuous_expCCL L (Λ_fam i) hL (hCCL i)).seqContinuous hconv

def IsIBOptimalPolicy {I : Type*}
    [MeasurableSpace I] [DiscreteMeasurableSpace I] (ζ : ProbabilityMeasure I)
    (Λ_fam : I → (Policy A O → Credal (Destiny A O))) : Policy A O → Prop :=
  fun π' => π' ∈ argminSet (fun π =>
    ∫ i, expCCL L (Λ_fam i) π ∂ζ.toMeasure
  )

/- Corollary 1:
Needs `Nonempty A`, otherwise policy space is empty.

The `[Nonempty A]` hypothesis was added to the target after the following counterexample:
without it the Corollary is false for `A := Empty`.  Then
  `ProbabilityMeasure A` is empty while `History A O` is not (it contains `[]`), so
  `Policy A O = History A O → ProbabilityMeasure A` is empty and no `π'` exists — yet every
  hypothesis is still satisfiable, because `Environment A O` (that is,
  `History A O → A → ProbabilityMeasure O`) is nonempty when `A` is empty (`fun _ a => a.elim`),
  so a crisp causal law does exist:

      example : ¬ (∀ (L : Destiny Empty Unit → unitInterval) (ζ : ProbabilityMeasure Unit)
            (Λ_fam : Unit → (Policy Empty Unit → Credal (Destiny Empty Unit))),
            Continuous L → (∀ i, IsCrispCausalLaw (Λ_fam i)) →
            ∃ π', IsIBOptimalPolicy L ζ Λ_fam π') := by
        intro h
        obtain ⟨π', -⟩ := h (fun d => (d 0).1.elim) ⟨Measure.dirac (), inferInstance⟩
          (fun _ => infraKernelOfEnvironments Set.univ ⟨fun _ a => a.elim, trivial⟩)
          (by continuity) (fun _ => ⟨Set.univ, ⟨fun _ a => a.elim, trivial⟩, rfl⟩)
        exact (isEmptyElim π' : False)

With `[Nonempty A]` — as `RLProofs.optimal_policy_exists` already does for the analogous RL
result — the Bayes loss is continuous (`continuous_integral_expCCL`), hence lower
semicontinuous, and `Policy A O` is compact, so the minimum is attained. -/
theorem exists_ib_optimal_policy {I : Type*}
    [MeasurableSpace I] [DiscreteMeasurableSpace I] (ζ : ProbabilityMeasure I)
    [Nonempty A]
    (Λ_fam : I → (Policy A O → Credal (Destiny A O)))
    (hL : Continuous L) (hCCL : ∀ i, IsCrispCausalLaw (Λ_fam i)) :
    ∃ π', IsIBOptimalPolicy L ζ Λ_fam π' := by
  obtain ⟨π', -, hmin⟩ :=
    LowerSemicontinuousOn.exists_isMinOn Set.univ_nonempty isCompact_univ
      ((continuous_integral_expCCL L ζ Λ_fam hL hCCL).lowerSemicontinuous.lowerSemicontinuousOn
        Set.univ)
  exact ⟨π', fun b => isMinOn_iff.mp hmin b (Set.mem_univ b)⟩

/-! ### Real-valued infra-regret

`infraRegret` is `EReal`-valued, but as soon as `Policy A O` is nonempty the infimum it
subtracts is a finite real (`expCCL` is `[0,1]`-valued), so the whole quantity is the
coercion of a real number.  Proposition 3 has no continuity hypotheses, so — unlike the RL
development, which uses the attained minimum `best_policy` — the work below is done with the
conditional infimum `⨅ π', expCCL L Λ π'` in `ℝ` and transported through
`infraRegret_eq_coe`. -/

/- The range of `expCCL` is bounded below by `0`, so its real infimum is well behaved. -/
lemma bddBelow_range_expCCL (Λ : Policy A O → Credal (Destiny A O)) :
    BddBelow (Set.range (expCCL L Λ)) :=
  ⟨0, by rintro x ⟨π, rfl⟩; exact (expCCL_mem_unitInterval L Λ π).1⟩

lemma ciInf_expCCL_le (Λ : Policy A O → Credal (Destiny A O)) (π : Policy A O) :
    ⨅ π', expCCL L Λ π' ≤ expCCL L Λ π :=
  ciInf_le (bddBelow_range_expCCL L Λ) π

lemma ciInf_expCCL_nonneg [Nonempty (Policy A O)] (Λ : Policy A O → Credal (Destiny A O)) :
    0 ≤ ⨅ π', expCCL L Λ π' :=
  le_ciInf fun π' => (expCCL_mem_unitInterval L Λ π').1

/- The real-valued infra-regret.  The machinery below is developed for this quantity. -/
noncomputable
def infraRegretR (Λ : Policy A O → Credal (Destiny A O)) (π : Policy A O) : ℝ :=
  expCCL L Λ π - ⨅ π', expCCL L Λ π'

/- The `EReal` infimum of a coerced, nonempty, bounded-below real family is the coercion of the
real infimum: `≥` is `ciInf_le` termwise, and `≤` holds because any `c` above the real infimum
is exceeded by some member of the family (`exists_lt_of_ciInf_lt`). -/
lemma coe_ciInf_expCCL [Nonempty (Policy A O)] (Λ : Policy A O → Credal (Destiny A O)) :
    ⨅ π', ((expCCL L Λ π' : ℝ) : EReal) = ((⨅ π', expCCL L Λ π' : ℝ) : EReal) := by
  refine le_antisymm (le_of_forall_gt_imp_ge_of_dense fun c hc => ?_)
    (le_iInf fun π' => EReal.coe_le_coe_iff.mpr (ciInf_expCCL_le L Λ π'))
  induction c using EReal.rec with
  | bot => exact absurd hc (by simp)
  | coe c =>
      obtain ⟨π', hπ'⟩ := exists_lt_of_ciInf_lt (by exact_mod_cast hc : ⨅ π', expCCL L Λ π' < c)
      exact le_trans (iInf_le _ π') (by exact_mod_cast hπ'.le)
  | top => exact le_top

/- `infraRegret` is the coercion of the real-valued infra-regret. -/
lemma infraRegret_eq_coe [Nonempty (Policy A O)] (Λ : Policy A O → Credal (Destiny A O))
    (π : Policy A O) :
    infraRegret L Λ π = ((infraRegretR L Λ π : ℝ) : EReal) := by
  rw [infraRegret, infraRegretR, EReal.coe_sub, coe_ciInf_expCCL]

lemma infraRegretR_nonneg (Λ : Policy A O → Credal (Destiny A O)) (π : Policy A O) :
    0 ≤ infraRegretR L Λ π :=
  sub_nonneg.2 (ciInf_expCCL_le L Λ π)

lemma infraRegretR_le_one [Nonempty (Policy A O)] (Λ : Policy A O → Credal (Destiny A O))
    (π : Policy A O) : infraRegretR L Λ π ≤ 1 := by
  have h1 := (expCCL_mem_unitInterval L Λ π).2
  have h2 := ciInf_expCCL_nonneg L Λ
  rw [infraRegretR]
  linarith

/- The `π`-independent term of the Bayes infra-regret is integrable: it is `[0,1]`-valued, and
measurable because `I` carries the discrete σ-algebra. -/
lemma integrable_ciInf_expCCL [Nonempty (Policy A O)] {I : Type*} [MeasurableSpace I]
    [DiscreteMeasurableSpace I] (ζ : ProbabilityMeasure I)
    (Λ_fam : I → (Policy A O → Credal (Destiny A O))) :
    Integrable (fun i => ⨅ π', expCCL L (Λ_fam i) π') ζ.toMeasure := by
  refine Integrable.mono' (integrable_const (μ := ζ.toMeasure) 1)
    Measurable.of_discrete.aestronglyMeasurable (Filter.Eventually.of_forall fun i => ?_)
  rw [Real.norm_eq_abs, abs_of_nonneg (ciInf_expCCL_nonneg L (Λ_fam i))]
  exact le_trans (ciInf_expCCL_le L (Λ_fam i) (Classical.arbitrary _))
    (expCCL_mem_unitInterval L (Λ_fam i) _).2

lemma integrable_infraRegretR [Nonempty (Policy A O)] {I : Type*} [MeasurableSpace I]
    [DiscreteMeasurableSpace I] (ζ : ProbabilityMeasure I)
    (Λ_fam : I → (Policy A O → Credal (Destiny A O))) (π : Policy A O) :
    Integrable (fun i => infraRegretR L (Λ_fam i) π) ζ.toMeasure :=
  (integrable_expCCL L ζ Λ_fam π).sub (integrable_ciInf_expCCL L ζ Λ_fam)

/- The Bayes infra-regret is the Bayes loss minus a `π`-independent constant. -/
lemma integral_infraRegretR_eq [Nonempty (Policy A O)] {I : Type*} [MeasurableSpace I]
    [DiscreteMeasurableSpace I] (ζ : ProbabilityMeasure I)
    (Λ_fam : I → (Policy A O → Credal (Destiny A O))) (π : Policy A O) :
    ∫ i, infraRegretR L (Λ_fam i) π ∂ζ.toMeasure
      = (∫ i, expCCL L (Λ_fam i) π ∂ζ.toMeasure)
        - ∫ i, (⨅ π', expCCL L (Λ_fam i) π') ∂ζ.toMeasure :=
  integral_sub (integrable_expCCL L ζ Λ_fam π) (integrable_ciInf_expCCL L ζ Λ_fam)

/- Hence an IB-optimal Policy also minimizes the Bayes infra-regret. -/
lemma ib_optimal_integral_infraRegretR_le [Nonempty (Policy A O)] {I : Type*} [MeasurableSpace I]
    [DiscreteMeasurableSpace I] (ζ : ProbabilityMeasure I)
    (Λ_fam : I → (Policy A O → Credal (Destiny A O)))
    {π' : Policy A O} (h_opt : IsIBOptimalPolicy L ζ Λ_fam π') (π : Policy A O) :
    ∫ i, infraRegretR L (Λ_fam i) π' ∂ζ.toMeasure
      ≤ ∫ i, infraRegretR L (Λ_fam i) π ∂ζ.toMeasure := by
  rw [integral_infraRegretR_eq, integral_infraRegretR_eq]
  exact sub_le_sub_right (h_opt π) _

/- Markov-type bound extracting a single index from the Bayes infra-regret. -/
lemma mass_mul_infraRegretR_le_integral [Nonempty (Policy A O)] {I : Type*} [MeasurableSpace I]
    [DiscreteMeasurableSpace I] (ζ : ProbabilityMeasure I)
    (Λ_fam : I → (Policy A O → Credal (Destiny A O))) (π : Policy A O) (i : I) :
    (ζ {i} : ℝ) * infraRegretR L (Λ_fam i) π
      ≤ ∫ j, infraRegretR L (Λ_fam j) π ∂ζ.toMeasure := by
  have h := setIntegral_le_integral (s := {i}) (integrable_infraRegretR L ζ Λ_fam π)
    (Filter.Eventually.of_forall fun j => infraRegretR_nonneg L (Λ_fam j) π)
  simpa [integral_singleton, mul_comm, NNReal.smul_def,
    ← ProbabilityMeasure.ennreal_coeFn_eq_coeFn_toMeasure] using h

end InfraRegret

section Learnability

/- Loss function now has a `γ` parameter -/
variable (L : discount → Destiny A O → unitInterval)

/- Definition: a policy family learns class of CCLs -/
def LearnsCCLClass {I : Type*}
    (Λ_fam : I → Policy A O → Credal (Destiny A O))
    (π_fam : discount → Policy A O) : Prop :=
  ∀ (i : I), Filter.Tendsto
  (fun (γ : discount) => infraRegret (L γ) (Λ_fam i) (π_fam γ)) Filter.atTop (nhds 0)

def NonAnytimeLearnableIB {I : Type*}
    (Λ_fam : I → Policy A O → Credal (Destiny A O)) : Prop :=
  ∃ π_fam, LearnsCCLClass L Λ_fam π_fam

/- The real-valued analogue of `LearnsCCLClass`, used by the Bayes machinery below. -/
def LearnsCCLClassR {I : Type*}
    (Λ_fam : I → Policy A O → Credal (Destiny A O))
    (π_fam : discount → Policy A O) : Prop :=
  ∀ (i : I), Filter.Tendsto
  (fun (γ : discount) => infraRegretR (L γ) (Λ_fam i) (π_fam γ)) Filter.atTop (nhds 0)

/- The two notions agree: `ℝ → EReal` is a topological embedding, so `EReal`-convergence of the
coerced infra-regret to `0 = ((0 : ℝ) : EReal)` is convergence of the real infra-regret. -/
lemma learnsCCLClass_iff [Nonempty (Policy A O)] {I : Type*}
    (Λ_fam : I → Policy A O → Credal (Destiny A O)) (π_fam : discount → Policy A O) :
    LearnsCCLClass L Λ_fam π_fam ↔ LearnsCCLClassR L Λ_fam π_fam := by
  unfold LearnsCCLClass LearnsCCLClassR
  refine forall_congr' fun i => ?_
  simp_rw [infraRegret_eq_coe, ← EReal.coe_zero]
  exact EReal.tendsto_coe

/- Dominated convergence (bound `1`) along `atTop : Filter discount`: if a policy family learns
the class, its Bayes infra-regret vanishes. -/
lemma integral_infraRegretR_tendsto_zero [Nonempty (Policy A O)] {I : Type*} [MeasurableSpace I]
    [DiscreteMeasurableSpace I] (ζ : ProbabilityMeasure I)
    (Λ_fam : I → Policy A O → Credal (Destiny A O)) (π_fam : discount → Policy A O)
    (h_learns : LearnsCCLClassR L Λ_fam π_fam) :
    Filter.Tendsto
      (fun γ : discount => ∫ i, infraRegretR (L γ) (Λ_fam i) (π_fam γ) ∂ζ.toMeasure)
      Filter.atTop (nhds 0) := by
  have h := tendsto_integral_filter_of_dominated_convergence (μ := ζ.toMeasure)
    (F := fun (γ : discount) i => infraRegretR (L γ) (Λ_fam i) (π_fam γ)) (f := fun _ => (0 : ℝ))
    (bound := fun _ => 1)
    (Filter.Eventually.of_forall fun γ => Measurable.of_discrete.aestronglyMeasurable)
    (Filter.Eventually.of_forall fun γ => Filter.Eventually.of_forall fun i => by
      rw [Real.norm_eq_abs, abs_of_nonneg (infraRegretR_nonneg (L γ) (Λ_fam i) (π_fam γ))]
      exact infraRegretR_le_one (L γ) (Λ_fam i) (π_fam γ))
    (integrable_const 1)
    (Filter.Eventually.of_forall fun i => h_learns i)
  simpa using h

/- Proposition 3 -/
theorem ib_optimal_learns_class {I : Type*}
    [MeasurableSpace I] [DiscreteMeasurableSpace I] (ζ : ProbabilityMeasure I)
    (Λ_fam : I → Policy A O → Credal (Destiny A O))
    (h_learn : NonAnytimeLearnableIB L Λ_fam)
    (h_non_dog : NonDogmaticPrior ζ)
    (π_fam : discount → Policy A O)
    (h_ib_opt : ∀ γ, IsIBOptimalPolicy (L γ) ζ Λ_fam (π_fam γ)) :
    LearnsCCLClass L Λ_fam π_fam := by
  -- the policy space is inhabited (by the given family), so all the real-valued machinery applies
  have : Nonempty (Policy A O) := ⟨π_fam ⟨0, by simp⟩⟩
  rw [learnsCCLClass_iff]
  intro i
  obtain ⟨π_fam', h_learns⟩ := h_learn
  rw [learnsCCLClass_iff] at h_learns
  -- the Bayes infra-regret of `π_fam` is squeezed between `0` and that of the learner `π_fam'`
  have hg : Filter.Tendsto
      (fun γ : discount => ∫ j, infraRegretR (L γ) (Λ_fam j) (π_fam γ) ∂ζ.toMeasure)
      Filter.atTop (nhds 0) :=
    squeeze_zero
      (fun γ => integral_nonneg fun j => infraRegretR_nonneg (L γ) (Λ_fam j) (π_fam γ))
      (fun γ => ib_optimal_integral_infraRegretR_le (L γ) ζ Λ_fam (h_ib_opt γ) (π_fam' γ))
      (integral_infraRegretR_tendsto_zero L ζ Λ_fam π_fam' h_learns)
  -- and the non-dogmatic prior gives index `i` positive mass, so its own regret vanishes
  have hc : (0 : ℝ) < (ζ {i} : ℝ) := by
    have h0 : 0 < ζ {i} := pos_iff_ne_zero.mpr (h_non_dog i)
    exact_mod_cast h0
  exact tendsto_zero_of_nonneg_of_mul_le hc
    (fun γ => infraRegretR_nonneg (L γ) (Λ_fam i) (π_fam γ))
    (fun γ => mass_mul_infraRegretR_le_integral (L γ) ζ Λ_fam (π_fam γ) i)
    hg

end Learnability

end RLSetting

end IB
