
import Mathlib

import AISafetyMath.Solutions.IB_RL
import AISafetyMath.Solutions.CredalSets
import AISafetyMath.Solutions.InfraKernel

/-
This file formalizes the definitions and propositions in
Articles/IB_Basics.md

The main result is `IB.infraKernelOfEnvironments_continuous`.
It also includes a number of sanity-check lemmas.

As with `IB_RL`, to keep this file readable the definitions and long proofs live in
helper files in this directory, which this file re-exposes:

* `AISafetyMath.Solutions.CredalSets` — the `IB` namespace development of credal sets:
  the metric space `Δ X` of probability measures (`convergence_iff_weak`), convexity of
  sets of probability measures (`ProbConvex`, `probConvex_iff`), the type `Credal X`
  of nonempty compact convex sets and its constructor `Credal.byClosedConvexHull`,
  and the Lévy–Prokhorov machinery used for continuity.

* `AISafetyMath.Solutions.InfraKernel` — the crisp causal laws: the infra-kernel
  generated by a set of environments (`IB.infraKernelOfEnvironments`) and Proposition 1
  (`IB.infraKernelOfEnvironments_continuous`: it is continuous in the Policy).

The reinforcement-learning definitions it builds on come transitively through
`AISafetyMath.Solutions.IB_RL`.
-/
