import Mathlib
import AISafetyMath.Solutions.CredalSets
import AISafetyMath.Solutions.TrajectoryMeasure

/-
Helper file (part 3): crisp causal laws / infra-kernels.

Imported by `Solutions.IB_Basics`.
-/

open ProbabilityTheory MeasureTheory

open scoped NNReal ENNReal

namespace IB

open scoped IB

open IB_RL

section CrispCausalLaws

variable {A O : Type*}
variable [Finite A] [Finite O]

/- we use discrete measurable and topological spaces on A and O -/
variable [MeasurableSpace A] [MeasurableSpace O]
variable [DiscreteMeasurableSpace A] [DiscreteMeasurableSpace O]
variable [TopologicalSpace A] [DiscreteTopology A]
variable [TopologicalSpace O] [DiscreteTopology O]


/- Instances making `Destiny A O` a compact metric Borel space and `Policy A O` a
topological space. These mirror the challenge file's local instances declaration by
declaration (same names, same `[Finite]`-only context, same bodies) so that the
statements below elaborate to literally the same terms as the challenge's; the
comparator requires syntactic equality of the elaborated statements. The root-level
instances in `Solutions.TrajectoryMeasure` are definitionally equal, but being
declared in a richer variable context they elaborate to different terms. -/

noncomputable local
instance instDestinyMetric : MetricSpace (Destiny A O) := PiNat.metricSpace


noncomputable local
instance instPolicyTS : TopologicalSpace (Policy A O) := Pi.topologicalSpace

/- Crisp Causal Laws: the infra-kernel generated by a set of environments.
Note that we say infraKernel here despite not yet knowing that the map is continuous. -/
noncomputable
def infraKernelOfEnvironments (E : Set (Environment A O)) (hne : E.Nonempty)
    (π : Policy A O) : Credal (Destiny A O) :=
    Credal.byClosedConvexHull
      ( (fun μ => trajectoryProbMeasure π μ) '' E)
      (Set.Nonempty.image (fun μ ↦ trajectoryProbMeasure π μ) hne)

/- Because `Policy A O` is a sequential space, to prove continuity it suffices to
prove the crisp causal law is *sequentially* continuous. -/
lemma proposition_1_of_seqContinuous (E : Set (Environment A O)) (hne : E.Nonempty)
    (h : SeqContinuous (infraKernelOfEnvironments E hne)) :
    Continuous (infraKernelOfEnvironments E hne) := by
  haveI : Fintype A := Fintype.ofFinite A
  haveI : Fintype O := Fintype.ofFinite O
  exact continuous_iff_seqContinuous.2 h

/- Proposition 1:
An infrakernel generated by environments is continuous. -/
theorem infraKernelOfEnvironments_continuous (E : Set (Environment A O)) (hne : E.Nonempty) :
    Continuous (infraKernelOfEnvironments E hne) := by
  haveI : Fintype A := Fintype.ofFinite A
  haveI : Fintype O := Fintype.ofFinite O
  apply proposition_1_of_seqContinuous
  intro π π₀ hconv
  -- The generating sets of the two credal carriers.
  set S : ℕ → Set (Δ (Destiny A O)) :=
    fun k => (fun μ => trajectoryProbMeasure (π k) μ) '' E with hS
  set S₀ : Set (Δ (Destiny A O)) :=
    (fun μ => trajectoryProbMeasure π₀ μ) '' E with hS₀
  -- LP-Hausdorff distance of the *generating* sets → 0, squeezed by the sup-over-`μ` bound (L4).
  have hSlp : Filter.Tendsto
      (fun k => Metric.hausdorffDist (lpEquiv '' S k) (lpEquiv '' S₀)) Filter.atTop (nhds 0) := by
    refine squeeze_zero (fun k => Metric.hausdorffDist_nonneg) (fun k => ?_)
      (trajectory_dist_iSup_tendsto_lp E π π₀ hconv)
    have e1 : lpEquiv '' S k = (fun μ => lpEquiv (trajectoryProbMeasure (π k) μ)) '' E := by
      rw [hS, Set.image_image]
    have e2 : lpEquiv '' S₀ = (fun μ => lpEquiv (trajectoryProbMeasure π₀ μ)) '' E := by
      rw [hS₀, Set.image_image]
    rw [e1, e2]
    exact hausdorffDist_image_le_biSup _ _ E hne
  -- Assemble: generating-set convergence → carrier convergence (IL7) → abstract metric (IL2).
  rw [tendsto_iff_dist_tendsto_zero]
  exact hausdorffDist_tendsto_zero_of_lp (hausdorffDist_lp_carrier_tendsto_zero hSlp)

end CrispCausalLaws

end IB
